// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'account_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_AccountModel _$$_AccountModelFromJson(Map<String, dynamic> json) =>
    _$_AccountModel(
      passWord: json['PassWord'] as String?,
      tradingPassword: json['TradingPassword'] as String?,
      loginName: json['LoginName'] as String?,
      source: json['Source'] as String?,
      ipClient: json['IpClient'] as String?,
      ipServer: json['IpServer'] as String?,
      aessionToken: json['AessionToken'] as String?,
      referer: json['Referer'] as String?,
      userAgent: json['UserAgent'] as String?,
      browser: json['Browser'] as String?,
      isMobile: json['IsMobile'] as String?,
      browserName: json['BrowserName'] as String?,
      browserVers: json['BrowserVers'] as String?,
      clientCode: json['ClientCode'] as String?,
      clientName: json['ClientName'] as String?,
      sessionNo: json['SessionNo'] as String?,
      errorCode: json['ErrorCode'] as int?,
      message: json['Message'] as String?,
      checkSession: json['CheckSession'] as int?,
      loginStatus: json['LoginStatus'] as int?,
      rsaToken: json['RsaToken'] as int?,
      checkTradingPassword: json['CheckTradingPassword'] as int?,
      rsaResult: json['RsaResult'] as int?,
      jwt: json['Jwt'] as String?,
      isCheckSessionSuccess: json['IsCheckSessionSuccess'] as bool?,
      isFirstLogin: json['IsFirstLogin'] as bool?,
      isRsaTokenTradingPassword: json['IsRsaTokenTradingPassword'] as bool?,
      rsaMessage: json['RsaMessage'] as String?,
      checkPass2: json['CheckPass2'] as int?,
      tradingPass1By1: json['TradingPass1By1'] as int?,
      oldPass: json['OldPass'] as String?,
      newPass: json['NewPass'] as String?,
      oldTradePass: json['OldTradePass'] as String?,
      newTradePass: json['NewTradePass'] as String?,
      intResult: json['IntResult'] as int?,
      areason: json['Areason'] as int?,
    );

Map<String, dynamic> _$$_AccountModelToJson(_$_AccountModel instance) =>
    <String, dynamic>{
      'PassWord': instance.passWord,
      'TradingPassword': instance.tradingPassword,
      'LoginName': instance.loginName,
      'Source': instance.source,
      'IpClient': instance.ipClient,
      'IpServer': instance.ipServer,
      'AessionToken': instance.aessionToken,
      'Referer': instance.referer,
      'UserAgent': instance.userAgent,
      'Browser': instance.browser,
      'IsMobile': instance.isMobile,
      'BrowserName': instance.browserName,
      'BrowserVers': instance.browserVers,
      'ClientCode': instance.clientCode,
      'ClientName': instance.clientName,
      'SessionNo': instance.sessionNo,
      'ErrorCode': instance.errorCode,
      'Message': instance.message,
      'CheckSession': instance.checkSession,
      'LoginStatus': instance.loginStatus,
      'RsaToken': instance.rsaToken,
      'CheckTradingPassword': instance.checkTradingPassword,
      'RsaResult': instance.rsaResult,
      'Jwt': instance.jwt,
      'IsCheckSessionSuccess': instance.isCheckSessionSuccess,
      'IsFirstLogin': instance.isFirstLogin,
      'IsRsaTokenTradingPassword': instance.isRsaTokenTradingPassword,
      'RsaMessage': instance.rsaMessage,
      'CheckPass2': instance.checkPass2,
      'TradingPass1By1': instance.tradingPass1By1,
      'OldPass': instance.oldPass,
      'NewPass': instance.newPass,
      'OldTradePass': instance.oldTradePass,
      'NewTradePass': instance.newTradePass,
      'IntResult': instance.intResult,
      'Areason': instance.areason,
    };
